### ISSUE TITLE
Error on  kubectl create -f orderer-service/

### ISSUE THREAD

**Issue by brunopaolo** [vanitas92/fabric-external-chaincodes#5]
Hi

When execute the command:  **kubectl create -f orderer-service/**

Can you help me ?

Thanks in advance
Paolo

I got this error:

2020-05-19 09:56:17.211 UTC [viperutil] getKeysRecursively -> DEBU 0d1 Found real value for general.LocalMSPID setting to string OrdererMSP
2020-05-19 09:56:17.211 UTC [viperutil] EnhancedExactUnmarshal -> DEBU 0d2 map[consensus:map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal] debug:map[BroadcastTraceDir:<nil> DeliverTraceDir:<nil>] fileledger:map[Location:/var/hyperledger/production/orderer Prefix:hyperledger-fabric-ordererledger] general:map[Authentication:map[NoExpirationChecks:<nil> TimeWindow:15m] BCCSP:map[Default:SW PKCS11:map[FileKeyStore:map[KeyStore:<nil>] Hash:<nil> Label:<nil> Library:<nil> Pin:<nil> Security:<nil>] SW:map[FileKeyStore:map[KeyStore:<nil>] Hash:SHA2 Security:256]] BootstrapFile:<nil> BootstrapMethod:file Cluster:map[CertExpirationWarningThreshold:<nil> ClientCertificate:/var/hyperledger/orderer/tls/server.crt ClientPrivateKey:/var/hyperledger/orderer/tls/server.key DialTimeout:<nil> ListenAddress:<nil> ListenPort:<nil> RPCTimeout:<nil> ReplicationBackgroundRefreshInterval:<nil> ReplicationBufferSize:<nil> ReplicationMaxRetries:<nil> ReplicationPullTimeout:<nil> ReplicationRetryTimeout:<nil> RootCAs:[/var/hyperledger/orderer/tls/ca.crt] SendBufferSize:10 ServerCertificate:<nil> ServerPrivateKey:<nil> TLSHandshakeTimeShift:<nil>] ConnectionTimeout:<nil> GenesisFile:/var/hyperledger/orderer/genesis.block GenesisMethod:file Keepalive:map[ServerInterval:7200s ServerMinInterval:60s ServerTimeout:20s] ListenAddress:0.0.0.0 ListenPort:7050 LocalMSPDir:/var/hyperledger/orderer/msp LocalMSPID:OrdererMSP Profile:map[Address:0.0.0.0:6060 Enabled:false] TLS:map[Certificate:/var/hyperledger/orderer/tls/server.crt ClientAuthRequired:false ClientRootCAs:<nil> Enabled:true PrivateKey:/var/hyperledger/orderer/tls/server.key RootCAs:[/var/hyperledger/orderer/tls/ca.crt]]] kafka:map[Retry:map[Consumer:map[RetryBackoff:2s] LongInterval:5m LongTotal:12h Metadata:map[RetryBackoff:250ms RetryMax:3] NetworkTimeouts:map[DialTimeout:10s ReadTimeout:10s WriteTimeout:10s] Producer:map[RetryBackoff:100ms RetryMax:3] ShortInterval:5s ShortTotal:10m] SASLPlain:map[Enabled:false Password:<nil> User:<nil>] TLS:map[Certificate:<nil> ClientAuthRequired:<nil> ClientRootCAs:<nil> Enabled:false PrivateKey:<nil> RootCAs:<nil>] Topic:map[ReplicationFactor:3] Verbose:false Version:<nil>] metrics:map[Provider:prometheus Statsd:map[Address:127.0.0.1:8125 Network:udp Prefix:<nil> WriteInterval:30s]] operations:map[ListenAddress:0.0.0.0:8443 TLS:map[Certificate:<nil> ClientAuthRequired:false ClientRootCAs:[] Enabled:false PrivateKey:<nil> RootCAs:<nil>]]]
2020-05-19 09:56:17.212 UTC [localconfig] completeInitialization -> WARN 0d3 General.GenesisFile should be replaced by General.BootstrapFile
2020-05-19 09:56:17.212 UTC [localconfig] completeInitialization -> INFO 0d4 Kafka.Version unset, setting to 0.10.2.0
2020-05-19 09:56:17.213 UTC [orderer.common.server] prettyPrintStruct -> INFO 0d5 Orderer config values:
        General.ListenAddress = "0.0.0.0"
        General.ListenPort = 7050
        General.TLS.Enabled = true
        General.TLS.PrivateKey = "/var/hyperledger/orderer/tls/server.key"
        General.TLS.Certificate = "/var/hyperledger/orderer/tls/server.crt"
        General.TLS.RootCAs = [/var/hyperledger/orderer/tls/ca.crt]
        General.TLS.ClientAuthRequired = false
        General.TLS.ClientRootCAs = []
        General.Cluster.ListenAddress = ""
        General.Cluster.ListenPort = 0
        General.Cluster.ServerCertificate = ""
        General.Cluster.ServerPrivateKey = ""
        General.Cluster.ClientCertificate = "/var/hyperledger/orderer/tls/server.crt"
        General.Cluster.ClientPrivateKey = "/var/hyperledger/orderer/tls/server.key"
        General.Cluster.RootCAs = [/var/hyperledger/orderer/tls/ca.crt]
        General.Cluster.DialTimeout = 5s
        General.Cluster.RPCTimeout = 7s
        General.Cluster.ReplicationBufferSize = 20971520
        General.Cluster.ReplicationPullTimeout = 5s
        General.Cluster.ReplicationRetryTimeout = 5s
        General.Cluster.ReplicationBackgroundRefreshInterval = 5m0s
        General.Cluster.ReplicationMaxRetries = 12
        General.Cluster.SendBufferSize = 10
        General.Cluster.CertExpirationWarningThreshold = 168h0m0s
        General.Cluster.TLSHandshakeTimeShift = 0s
        General.Keepalive.ServerMinInterval = 1m0s
        General.Keepalive.ServerInterval = 2h0m0s
        General.Keepalive.ServerTimeout = 20s
        General.ConnectionTimeout = 0s
        General.GenesisMethod = "file"
        General.GenesisFile = "/var/hyperledger/orderer/genesis.block"
        General.BootstrapMethod = "file"
        General.BootstrapFile = "/var/hyperledger/orderer/genesis.block"
        General.Profile.Enabled = false
        General.Profile.Address = "0.0.0.0:6060"
        General.LocalMSPDir = "/var/hyperledger/orderer/msp"
        General.LocalMSPID = "OrdererMSP"
        General.BCCSP.ProviderName = "SW"
        General.BCCSP.SwOpts.SecLevel = 256
        General.BCCSP.SwOpts.HashFamily = "SHA2"
        General.BCCSP.SwOpts.Ephemeral = true
        General.BCCSP.SwOpts.FileKeystore.KeyStorePath = ""
        General.BCCSP.SwOpts.DummyKeystore =
        General.BCCSP.SwOpts.InmemKeystore =
        General.Authentication.TimeWindow = 15m0s
        General.Authentication.NoExpirationChecks = false
        FileLedger.Location = "/var/hyperledger/production/orderer"
        FileLedger.Prefix = "hyperledger-fabric-ordererledger"
        Kafka.Retry.ShortInterval = 5s
        Kafka.Retry.ShortTotal = 10m0s
        Kafka.Retry.LongInterval = 5m0s
        Kafka.Retry.LongTotal = 12h0m0s
        Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
        Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
        Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
        Kafka.Retry.Metadata.RetryMax = 3
        Kafka.Retry.Metadata.RetryBackoff = 250ms
        Kafka.Retry.Producer.RetryMax = 3
        Kafka.Retry.Producer.RetryBackoff = 100ms
        Kafka.Retry.Consumer.RetryBackoff = 2s
        Kafka.Verbose = false
        Kafka.Version = 0.10.2.0
        Kafka.TLS.Enabled = false
        Kafka.TLS.PrivateKey = ""
        Kafka.TLS.Certificate = ""
        Kafka.TLS.RootCAs = []
        Kafka.TLS.ClientAuthRequired = false
        Kafka.TLS.ClientRootCAs = []
        Kafka.SASLPlain.Enabled = false
        Kafka.SASLPlain.User = ""
        Kafka.SASLPlain.Password = ""
        Kafka.Topic.ReplicationFactor = 3
        Debug.BroadcastTraceDir = ""
        Debug.DeliverTraceDir = ""
        Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
        Operations.ListenAddress = "0.0.0.0:8443"
        Operations.TLS.Enabled = false
        Operations.TLS.PrivateKey = ""
        Operations.TLS.Certificate = ""
        Operations.TLS.RootCAs = []
        Operations.TLS.ClientAuthRequired = false
        Operations.TLS.ClientRootCAs = []
        Metrics.Provider = "prometheus"
        Metrics.Statsd.Network = "udp"
        Metrics.Statsd.Address = "127.0.0.1:8125"
        Metrics.Statsd.WriteInterval = 30s
        Metrics.Statsd.Prefix = ""
2020-05-19 09:56:17.213 UTC [bccsp] GetDefault -> DEBU 0d6 Before using BCCSP, please call InitFactories(). Falling back to bootBCCSP.
2020-05-19 09:56:17.214 UTC [bccsp_sw] createKeyStore -> DEBU 0d7 Creating KeyStore at [/var/hyperledger/orderer/msp/keystore]...
2020-05-19 09:56:17.214 UTC [bccsp_sw] createKeyStore -> DEBU 0d8 KeyStore created at [/var/hyperledger/orderer/msp/keystore].
2020-05-19 09:56:17.214 UTC [bccsp_sw] openKeyStore -> DEBU 0d9 KeyStore opened at [/var/hyperledger/orderer/msp/keystore]...done
2020-05-19 09:56:17.214 UTC [msp] getPemMaterialFromDir -> DEBU 0da Reading directory /var/hyperledger/orderer/msp/signcerts
2020-05-19 09:56:17.214 UTC **[orderer.common.server] loadLocalMSP -> PANI 0db Failed to get l**ocal msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory
panic: Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory****

goroutine 1 [running]:
github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ba6e0, 0x0, 0x0, 0x0)
        /go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:230 +0x545
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc000116220, 0x4, 0x1006f4c, 0x22, 0xc000283530, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x100
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)
        /go/src/github.com/hyperledger/fabric/common/flogging/zap.go:74
github.com/hyperledger/fabric/orderer/common/server.loadLocalMSP(0xc00019e000, 0xc000166000, 0x0)
        /go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:664 +0x10b
github.com/hyperledger/fabric/orderer/common/server.Main()
        /go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:91 +0x252
main.main()
        /go/src/github.com/hyperledger/fabric/cmd/orderer/main.go:15 +0x20

**Comment by vanitas92** [comment]
Hi @brunopaolo ,

Can you make sure that after executing the `fabricOps.sh` script, the crypto-config folder is populated with the certificates? Seems like they have not been created or the folder pointing in `hostpath` in the orderer deployment yaml do not point correctly in the local machine where the certificates should be.

Thanks!

**Comment by vanitas92** [comment]
Closing since no feedback received for 10 days

**Comment by AlexMesser** [comment]
faced the same issue in Windows. Seems like this example is working only on UNIX systems, because `/home/` directory obviously does not exist in Windows. The solution is to use environment variables instead of hardcoded paths

UPD:
I tried to use the absolute path in volumes like  `/C/Users/` and `C:/Users` and others, but it does not work due to known issues with mounting volumes in Windows

**Comment by brando14** [comment]
hello, i have the same issue and i have already verified that the certificates were created, and that they point to the correct direction in the yaml.


I am using a gcp cluster (google kubernetes cluster) and a vm ubuntu 20.04 lts, ​​as an environment to perform the deployment.

any idea why this is?
